biomage-org/ui

package-lock.json, package.json, src/components/data-processing/ConfigureEmbedding/ConfigureEmbedding.jsx, src/components/plots/CategoricalEmbeddingPlot.jsx, src/components/plots/styling/PlotStyling.jsx, src/components/plots/styling/PointDesign.jsx, src/utils/plotSpecs/generateEmbeddingCategoricalSpec.js
Use WebGL renderer to render the plots in Configure embedding
https://biomage.atlassian.net/browse/BIOMAGE-2046
N/A
master
=> Render plots in configure embedding on the gpu

src/__test__/utils/plotSpecs/__snapshots__/generateViolinSpec.test.js.snap, src/__test__/utils/plotSpecs/generateViolinSpec.test.js, src/pages/experiments/[experimentId]/plots-and-tables/embedding-categorical/index.jsx, src/utils/plotSpecs/generateEmbeddingCategoricalSpec.js, src/utils/plotSpecs/generateFrequencySpec.js, src/utils/plotSpecs/generateHeatmapSpec.js, src/utils/plotSpecs/generateViolinSpec.js
One of the bugs was when there are a lot of clusters and plotting the legend on the right was clipping them if the height was not enough to show all the clusters in the legend. I made a change so if there are more than 20 clusters to add a new column to the legend.
https://biomage.atlassian.net/browse/BIOMAGE-2063
https://ui-grasp6-ui23.scp-staging.biomage.net/
master
=> [BIOMAGE-2063] User Qi reported bugs with incorrect legends in plots and tables

src/pages/_app.jsx
If users ar eusing the old urls (expid iwthotu dashes), it wont break completely, but some behavior might be odd, to avoid this we can replace any expeirment id in the url without dashes with their dashed version
N/A
https://ui-martinfosco-ui30.scp-staging.biomage.net/
master
=> Hotfix add handling for old experiment id in url

src/components/data-processing/GenesVsUMIs/CalculationConfig.jsx, src/components/data-processing/GenesVsUMIs/GenesVsUMIs.jsx, src/pages/experiments/[experimentId]/data-processing/index.jsx
There's a qc rerun button that I missed when working in the merge-qc tickets, it needs to display the clone/run gem2s modal  as well, so this PR is doing that.
This run qc button shows up only when the user is in genes vs umis and hasn't run qc in the last 4/5 weeks. (it is to ask them to run it in order to see a new feature in the plots).
N/A
https://ui-martinfosco-ui31.scp-staging.biomage.net/
master
**will not pass** the required status checks …
=> Add qcRerunModal for new feature suggestion

src/__test__/components/data-exploration/generic-gene-table/ExpressionCellSetModal.test.jsx, src/__test__/components/plots/ViolinPlot.test.jsx, src/__test__/pages/experiments/[experimentId]/data-processing/index.test.jsx, src/__test__/redux/actions/cellMeta/loadCellMeta.test.js, src/__test__/redux/actions/pipelines/runQC.test.js, src/__test__/utils/work/seekWorkResponse.test.js, src/pages/experiments/[experimentId]/data-processing/index.jsx
Fix uncaught exception tests.
To check, clone the branch and run `npm test`.
N/A
N/A
N/A
master
=> Fix uncaught test exceptions

src/__test__/pages/experiments/[experimentId]/plots-and-tables/index.test.jsx, src/components/plots/PlotsTablesContainer.jsx
Hide trajectory analysis because it's not showing the correct result
https://ui-agi-ui43.scp-staging.biomage.net/
N/A
N/A
N/A
master
=> Hide trajectory analysis plot

src/components/data-management/FileUploadModal.jsx, src/utils/upload/fileUploadSpecifications.js
https://biomage.atlassian.net/browse/BIOMAGE-1698
https://ui-grasp6-ui46.scp-staging.biomage.net/data-management
master
=> [BIOMAGE-1698] Update upload samples modal for supporting BD rhapsody option 

src/__test__/pages/experiments/[experimentId]/plots-and-tables/dot-plot/index.test.jsx, src/components/plots/styling/SelectData.jsx, src/utils/upload/fileUploadSpecifications.js
=> Fix dot plot test randomly failing

src/components/data-management/SamplesTable.jsx, src/components/data-management/SamplesTableCells.jsx, src/utils/upload/fileUploadSpecifications.js
https://biomage.atlassian.net/browse/BIOMAGE-1760
https://ui-stefan-ui47.scp-staging.biomage.net/
master
=> [BIOMAGE-1760] Make the uploaded samples table generic

src/components/plots/TrajectoryAnalysisPlot.jsx, src/components/plots/helpers/heatmap/populateHeatmapData.js, src/components/plots/helpers/heatmap/vega/utils/generateVegaHeatmapTracksData.js
In [this thread](https://this-is-biomage.slack.com/archives/C036HK7S2R0/p1663786563445209?thread_ts=1663786288.435589&cid=C036HK7S2R0)
N/A
https://ui-martinfosco-ui51.scp-staging.biomage.net/
master
=> [HOTFIX] Array concatenation exceeds stack size

src/components/data-exploration/embedding/Embedding.jsx
N/A
https://ui-martinfosco-ui55.scp-staging.biomage.net/
master
=> [HOTFIX] Tooltips in embedding are one hover apart from the ones in the marker heatmap

.github/workflows/ci.yaml, jest.config.js, package.json
Locally the issue seemed to be a simple timeout so I've increased the timeout limit. At the same time, the command we use to run tests was `jest --silent --runInBand --bail` while the one used to run the coverage had different parameters `jest --coverage --silent`. I've added the `--runInBand --bail` to make the CI run the same as when we run without coverage.
https://biomage.atlassian.net/browse/BIOMAGE-2141
N/A
master
**will not pass** the …
=> [BIOMAGE-2141] Fixing failing coverage

src/config/defaultConfig.js
This PR is to set the worker version to from 1 to 2. This is to invalide all worker results after [this PR](https://github.com/biomage-org/worker/pull/29), which fixes some wrong volcano plots, was released.
N/A
N/A
master
=> Change worker version to 2 to invalidate worker results

src/__test__/pages/experiments/[experimentId]/plots-and-tables/normalized-matrix/index.test.jsx, src/__test__/redux/actions/genes/__snapshots__/loadPaginatedGeneProperties.test.js.snap, src/__test__/utils/work/fetchWork.test.js, src/__test__/utils/work/generateETag.test.js, src/redux/actions/cellMeta/loadCellMeta.js, src/redux/actions/componentConfig/downloadNormalizedMatrix.js, src/utils/work/getExtraDependencies.js
=> Fix weird merge

src/utils/work/generateETag.js, src/utils/work/workerVersions.js
=> Invalidate gene expression

src/__test__/utils/work/fetchWork.test.js, src/__test__/utils/work/generateETag.test.js
=> Invalidate genee xpression update tsts

src/__test__/components/plots/PlotStyling.test.jsx, src/components/plots/styling/volcano/DisplayLabels.jsx, src/pages/experiments/[experimentId]/plots-and-tables/volcano/index.jsx
The slider under `Gene Labels` in the volcano plot has insufficient precision for some experiments. The slider can be changed to a number box to allow better customisability.
https://biomage.atlassian.net/browse/BIOMAGE-2226
https://ui-martinfosco-ui96.scp-staging.biomage.net/
master
=> [BIOMAGE-2226] Add number box to volcano plot label threshold

src/__test__/components/data-management/DownloadDataButton.test.jsx, src/components/data-management/DownloadDataButton.jsx
https://biomage.atlassian.net/browse/BIOMAGE-2237
N/A
master
=> [BIOMAGE-2237] Removed option to download raw rds object

src/components/data-processing/DataIntegration/NormalisationOptions.jsx
Enable the SCTransform button.
N/A
N/A
master
=> [BIOMAGE-2059] Enable sctransform

.github/workflows/ci.yaml, src/__test__/components/data-processing/configure-embedding/ConfigureEmbedding.test.jsx, src/components/data-processing/ConfigureEmbedding/ConfigureEmbedding.jsx
https://biomage.atlassian.net/browse/BIOMAGE-2250
https://ui-ahriman-ui104.scp-staging.biomage.net/
master
=> [BIOMAGE-2250] Removed miniplots in configure embeddings

src/components/data-processing/DataIntegration/NormalisationOptions.jsx
Update the tooltip to specify that SCTransform can only be used with Seurat v4 as the integration method.
N/A
N/A
master
=> Update normalization tooltip

src/components/SliderWithInput.jsx, src/components/data-processing/ConfigureEmbedding/CalculationConfig.jsx
Increase clustering resolution
https://ui-agi-ui116-api60.scp-staging.biomage.net/
https://biomage.atlassian.net/browse/BIOMAGE-2272
N/A
API - https://github.com/biomage-org/api/pull/60
UI - https://github.com/biomage-org/ui/pull/116
master
=> [BIOMAGE-2272] - Increase clustering resolution

src/__test__/redux/actions/differentialExpression/__snapshots__/loadDifferentialExpression.test.js.snap, src/__test__/redux/actions/differentialExpression/loadDifferentialExpression.test.js, src/redux/actions/differentialExpression/loadDifferentialExpression.js
https://biomage.atlassian.net/browse/BIOMAGE-2300
N/A
master
=> [BIOMAGE-2300] Fixed differential expression between samples

src/__test__/redux/actions/differentialExpression/__snapshots__/loadDifferentialExpression.test.js.snap, src/__test__/redux/actions/differentialExpression/loadDifferentialExpression.test.js
https://biomage.atlassian.net/browse/BIOMAGE-2300
N/A
master
=> [BIOMAGE-2300] Added test for comparison between samples

src/__test__/redux/actions/differentialExpression/__snapshots__/loadDifferentialExpression.test.js.snap, src/__test__/redux/actions/differentialExpression/loadDifferentialExpression.test.js
Just removing a test that was duplicated inadvertently.
N/A
N/A
master
=> removed duplicated test

.github/workflows/ci.yaml, src/__test__/components/data-exploration/cell-sets-tool/CellSetsTool.test.jsx, src/__test__/components/data-exploration/cell-sets-tool/SubsetCellSetsOperation.test.jsx, src/components/data-exploration/cell-sets-tool/CellSetsTool.jsx, src/components/data-exploration/cell-sets-tool/SubsetCellSetsModal.jsx, src/components/data-exploration/cell-sets-tool/SubsetCellSetsOperation.jsx, src/redux/actions/pipeline/index.js, src/redux/actions/pipeline/runSubsetExperiment.js
https://biomage.atlassian.net/browse/BIOMAGE-2251
N/A (in the api)
https://github.com/biomage-org/api/pull/63
https://github.com/biomage-org/pipeline/pull/85
master
=> [2251] Add basic endpoint for creating new subset pipeline

src/utils/plotSpecs/generateFrequencySpec.js
https://biomage.atlassian.net/browse/BIOMAGE-2282
https://ui-martinfosco-ui133.scp-staging.biomage.net/
master
=> [2282] Improve performance of frequency plot data generation

src/redux/reducers/componentConfig/initialState.js, src/utils/constants.js
This is a preliminary step for implementing saved plots. It fixes the plot types and adds default plot uuids to `constants.js` to avoid hardcoding, and creates a new initial config state for the saved plots component. Customizable components loading can be reused from the multi view implementation (`loadConditionalComponentConfig`).
https://biomage.atlassian.net/browse/BIOMAGE-2295
https://ui-martinfosco-ui136.scp-staging.biomage.net/
master …
=> Add saved plots required constants

src/utils/integrationTestConstants.js
=> Add comment with more explanation of why the cypress constants file exists

src/components/data-management/SamplesTable.jsx
https://biomage.atlassian.net/browse/BIOMAGE-2311
https://ui-grasp6-ui139.scp-staging.biomage.net/
master
=> [BIOMAGE-2311] Clicking button "Add metadata" and afterwards clicking cancel gives an error

src/components/data-exploration/embedding/Embedding.jsx
Make the tooltip disappear if it's not on top of a cell.
https://biomage.atlassian.net/browse/BIOMAGE-2292
https://ui-agi-ui143.scp-staging.biomage.net/
N/A
N/A
master
[BIOMAGE-2292]: https://biomage.atlassian.net/browse/BIOMAGE-2292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BIOMAGE-2292] - Hide cellinfo after action

src/__test__/utils/work/seekWorkResponse.test.js, src/utils/work/seekWorkResponse.js
https://biomage.atlassian.net/browse/BIOMAGE-2244
https://ui-ahriman-ui153.scp-staging.biomage.net/
master
=> [BIOMAGE-2244] Fixed missing timeout parameter for some work requests

src/redux/reducers/samples/samplesFileUpdate.js, src/utils/data-management/generateGem2sParamsHash.js
https://biomage.atlassian.net/browse/BIOMAGE-2340
N/A https://ui-martinfosco-ui152.scp-staging.biomage.net/
master
=> Fixes to gem2s hashing

src/components/data-processing/ConfigureEmbedding/ConfigureEmbedding.jsx, src/components/data-processing/DataIntegration/DataIntegration.jsx
https://biomage.atlassian.net/browse/BIOMAGE-2360
N/A
master
=> [BIOMAGE-2360] Set plotView items to minHeight to allow box resizing

src/components/data-exploration/cell-sets-tool/CellSetsTool.jsx
Even though subset works, we are still missing the ui-side updates handling for subset. Forgot to comment out this button when I merged in my PR yesterday
N/A
N/A
master
=> Comment out subset cell sets button

src/config/defaultConfig.js
This PR is to set the worker version to from 2 to 3. This is to invalide all worker results after https://github.com/biomage-org/worker/pull/63, which fixes some wrong volcano plots, was released.
N/A
N/A
master
=> Change worker version to 3 to invalidate worker results

src/__test__/pages/repository/index.test.jsx
https://biomage.atlassian.net/browse/BIOMAGE-2388
N/A
master
=> Add some tests for the repository page

src/__test__/components/data-exploration/generic-gene-table/__snapshots__/ExpressionCellSetModal.test.jsx.snap, src/__test__/redux/actions/embeddings/__snapshots__/loadEmbedding.defaultParams.test.js.snap, src/__test__/redux/actions/embeddings/loadEmbedding.defaultParams.test.js, src/__test__/redux/actions/genes/__snapshots__/loadMarkerGenes.defaultParams.test.js.snap, src/__test__/redux/actions/genes/__snapshots__/loadPaginatedGeneProperties.test.js.snap, src/__test__/redux/actions/genes/loadMarkerGenes.defaultParams.test.js, src/__test__/utils/work/fetchWork.test.js, src/__test__/utils/work/generateETag.test.js, src/config/defaultConfig.js, src/config/testConfig.js, src/utils/work/createObjectHash.js, src/utils/work/generateETag.js
https://biomage.atlassian.net/browse/BIOMAGE-2301
N/A
https://github.com/biomage-org/ui/pull/183
https://github.com/biomage-org/api/pull/110
master
=> [BIOMAGE-2301] Tests for default embedding & marker heatmap ETags

src/components/ContentWrapper.jsx
https://biomage.atlassian.net/browse/BIOMAGE-2302
N/A https://ui-martinfosco-ui179-api113.scp-staging.biomage.net/
https://github.com/biomage-org/api/pull/113
master
=> [2302] Resume qc from error

src/__test__/components/data-exploration/generic-gene-table/LaunchPathwayAnalysisModal.test.jsx, src/components/data-exploration/differential-expression-tool/LaunchPathwayAnalysisModal.jsx
=> Change default to enrichr

src/components/data-exploration/embedding/CrossHair.jsx, src/components/data-exploration/embedding/Embedding.jsx, src/components/data-exploration/heatmap/HeatmapPlot.jsx
The embedding tooltip flickered because whenever we mouse over an embedding point it will show the tooltip **and** a grid. 
If the mouse pointer hovers over that grid, the embedding (which is underneath that grid) will detect that the pointer left that cell (and the embedding altogether) since it is now over the grid, so it stops appearing and it detects it again once we move away from the grid line. Usually these two actions are perceived as a flicker because the grid is very thin
The fix is: make grid not trigger hover events (so the embedding underneath isn't affected by it)
N/A
N/A
master
**You must check the box below** to run …
=> Fix flickering of tooltip on embedding

src/components/data-exploration/cell-sets-tool/AnnotateClustersTool.jsx
https://biomage.atlassian.net/browse/BIOMAGE-2423
N/A
master
=> [2423] Add tooltip to scType

src/__test__/pages/experiments/[experimentId]/plots-and-tables/violin/__snapshots__/index.test.jsx.snap, src/__test__/pages/experiments/[experimentId]/plots-and-tables/violin/index.test.jsx, src/pages/experiments/[experimentId]/plots-and-tables/violin/index.jsx
https://biomage.atlassian.net/browse/BIOMAGE-2444
N/A
https://ui-martinfosco-ui205.scp-staging.biomage.net/
master
=> [2444] Facetted violin plot defaults to original grouping when adding new genes

src/components/data-management/NewProjectModal.jsx
Pretty sefl-explanatory. Typing enter on the title input will create the project instead of closing the modal.
https://biomage.atlassian.net/browse/BIOMAGE-1962
N/A https://ui-ahriman-ui221.scp-staging.biomage.net/data-management
N/A
master
=> [BIOMAGE-1962] Create project on typing enter

.github/workflows/ci.yaml, .github/workflows/nextjs_bundle_analysis.yaml, .github/workflows/pr_validate.yaml
=> Fix PR formatting

src/__test__/components/header/ReferralButton.test.jsx, src/components/header/ReferralButton.jsx
Add domain to referral messages
https://github.com/biomage-org/issues/issues/94
N/A
N/A
N/A
master
=> Add domain to referral button

src/__test__/components/data-management/ProjectDetails.test.jsx, src/__test__/redux/reducers/__snapshots__/experimentsReducer.test.js.snap, src/components/ContentWrapper.jsx, src/components/data-management/AddMetadataButton.jsx, src/components/data-management/ProjectDetails.jsx, src/components/data-management/ProjectMenu.jsx, src/components/data-management/SamplesTable.jsx, src/redux/actions/experiments/loadExperiments.js, src/redux/reducers/experiments/initialState.js
https://biomage.atlassian.net/browse/BIOMAGE-2438
https://ui-explorer-subset.scp-staging.biomage.net/data-management
https://github.com/biomage-org/ui/pull/228
https://github.com/biomage-org/api/pull/146
master
=> [BIOMAGE-2438] Make Subset feature work for Explorers

src/__test__/components/header/HelpButton.test.jsx, src/components/Header.jsx, src/components/data-management/CoursesBanner.jsx, src/components/header/HelpButton.jsx, src/pages/data-management/index.jsx
=> courses banner 

src/utils/data-management/experimentSharing/sendInvites.js, src/utils/endUserMessages.jsx
N/A
N/A (in api)
https://github.com/biomage-org/api/pull/150
master
=> Add share error handling

src/__test__/pages/experiments/[experimentId]/plots-and-tables/batch-differential-expression/index.test.jsx, src/pages/experiments/[experimentId]/plots-and-tables/batch-differential-expression/index.jsx, src/utils/extraActionCreators/differentialExpression/checkCanRunDiffExpr.js, src/utils/extraActionCreators/differentialExpression/getBatchDiffExpr.js
There were two issues:
1. I missed a case where the comparison option was passed to the worker in the pattern `<rootCluster>/<clusterName>` it should be passed without the `rootCluster/`
2. In the third option in Batch differential expression, the requests should be passed, using `within` option. The `between` was crashing the worker so changing it seemed to fix it.
3. The second option is `between`
https://biomage.atlassian.net/browse/BIOMAGE-2454
https://ui-batchde-fix.scp-staging.biomage.net/
master
Integration tests have to pass …
=> [BIOMAGE-2454] Batch differential expression within samples broken

src/components/GEM2SLoadingScreen.jsx, src/redux/actions/experiments/cloneExperiment.js, src/utils/endUserMessages.jsx, src/utils/http/httpStatusCodes.js
N/A
https://github.com/orgs/biomage-org/projects/2/views/1?pane=issue&itemId=28571163
N/A
https://github.com/biomage-org/pipeline/pull/159
https://github.com/biomage-org/api/pull/151
master
=> [87] Clone experiment with annotations

src/__test__/components/ContentWrapper.test.jsx, src/components/ContentWrapper.jsx, src/utils/data-management/calculateGem2sRerunStatus.js
issue:
https://github.com/orgs/biomage-org/projects/2/views/6?pane=issue&itemId=30829160
N/A
N/A
master
=> Disable Data Processing, Data Management and Plots and Tables module when opening up the public datasets respository page.

src/components/data-management/FileUploadModal.jsx
=> Commented line to test h5 upload

.gitattributes
=> hotfixes for hms merge

.flux.yaml, .github/workflows/ci.yaml
=> fixed path in .flux

.github/workflows/ci.yaml
=> changed owner variable

.github/workflows/pr_validate.yaml
=> Remove check-issue-url

src/__test__/components/header/HelpButton.test.jsx
https://github.com/orgs/biomage-org/projects/2/views/1?pane=issue&itemId=33824377
https://github.com/hms-dbmi-cellenics/ui/pull/848#discussion_r1268600781
N/A
master
=> Example domain specific test

next.config.js, src/components/Header.jsx, src/components/TagManager.jsx, src/components/header/HelpButton.jsx, src/config/defaultConfig.js, src/pages/experiments/[experimentId]/plots-and-tables/batch-differential-expression/index.jsx, src/utils/deploymentInfo.js, src/utils/domainSpecificContent.jsx, src/utils/getDomainSpecificContent.jsx, src/utils/tracking.js
https://github.com/orgs/biomage-org/projects/2/views/1?pane=issue&itemId=33824377
Adressed comments (for context and explanations):
https://github.com/hms-dbmi-cellenics/ui/pull/848#discussion_r1269845060
https://github.com/hms-dbmi-cellenics/ui/pull/848#discussion_r1269848795
https://github.com/hms-dbmi-cellenics/ui/pull/848#discussion_r1269866861
https://github.com/hms-dbmi-cellenics/ui/pull/848#discussion_r1269893784
https://github.com/hms-dbmi-cellenics/ui/pull/848#discussion_r1269902926
https://github.com/hms-dbmi-cellenics/ui/pull/848/files/876e705c278c9cf85de834734a73d60f8246b4e5#r1269889314
N/A https://ui-martinfosco-ui250.scp-staging.biomage.net/
master
Have best practices and ongoing …
=> Address hms code review comments

src/pages/experiments/[experimentId]/plots-and-tables/batch-differential-expression/index.jsx
https://github.com/orgs/biomage-org/projects/2/views/1?pane=issue&itemId=32307045
https://ui-grasp6-ui251.scp-staging.biomage.net/
master
=> Batch differential expression file naming

src/__test__/utils/deploymentInfo.test.js, src/utils/deploymentInfo.js
=> Fix default in dev account
